### ISSUE TITLE
Infinite build times for Synchronous Instantiation of some Languages

### ISSUE THREAD

**Issue by TrueHorse** [xErik/hyphenatorx#6]
This is probably a problem on flutters end, but I thought you might understand the cause and be able to explain it to them, which is why I report it here for now.
When running "flutter build windows" while having the following code in my project, the build will just run forever (or at least >30 min, cancled after that) for some, but not all languages.
`[...]
children: [
                                    Hyphenator(Language_de_1996()).wrap(
                                        Text(
                                            selectedArticle.title!,
                                            softWrap: true,
                                            textAlign: TextAlign.center,
                                            style: Theme.of(context).textTheme.headlineMedium
                                        ),
                                        Theme.of(context).textTheme.headlineMedium!,
                                        1.0).text,
                                    Padding(
[...]`

I tested all german languange codes, Hungarian, Finnish, Dutch and US-English and only Finnish and English finished in a reasonable amount of time.
Building in debug mode works normally.

The problem seams to be that the "aot elf release" snapshot creation gets stuck. The gen_snapshot.exe "never" exits.

These are my build log as well as my flutter doctor output:
[build log.txt](https://github.com/user-attachments/files/15804825/build.log.txt)
[doctor.txt](https://github.com/user-attachments/files/15804876/doctor.txt)

**Comment by TrueHorse** [comment]
Building with the --debug flag works, yes.
I didn't try the reinitalization, but it doesn't seem to help either.
Regarding the log, the build got stuck after line 250, so after `C:\Users\paul.ross\StudioProjects\eurocisdemo\.dart_tool\flutter_build\97766e2f9d3c075c85c50ec8d45a0fe6\app.dill`. The rest of the lines, so

`[+1202203 ms] ensureAnalyticsSent: 21ms
[        ] Running 0 shutdown hooks
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0
Batchvorgang abbrechen (J/N)? j`

appeared after I ctr + c it.

I also shut it (gen_snapshot.exe) down via the task manager once, which resulted in this:
`C:\Users\paul.ross\StudioProjects\eurocisdemo\.dart_tool\flutter_build\97766e2f9d3c075c85c50ec8d45a0fe6\app.dill
[+366905 ms]   [+366900 ms] Dart snapshot generator failed with exit code 1
[   +2 ms]   [   +4 ms] Persisting file store
[ +106 ms]   [ +108 ms] Done persisting file store
[  +31 ms]   [  +31 ms] Target aot_elf_release failed: Exception: AOT snapshotter exited with code 1
[   +3 ms]              #0      AotElfBase.build (package:flutter_tools/src/build_system/targets/common.dart:332:7)
[   +9 ms]              <asynchronous suspension>
[   +4 ms]              #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
[   +2 ms]              <asynchronous suspension>
[        ]              #2      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
[        ]              <asynchronous suspension>
[   +3 ms]              #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
[        ]              <asynchronous suspension>
[        ]              #4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
[  +10 ms]              <asynchronous suspension>
[        ]              #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
[        ]              <asynchronous suspension>
[   +1 ms]              #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
[        ]              <asynchronous suspension>
[   +2 ms]              #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:322:32)
[        ]              <asynchronous suspension>
[        ]              #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
[        ]              <asynchronous suspension>
[        ]              #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]              <asynchronous suspension>
[        ]              #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]              <asynchronous suspension>
[   +1 ms]              #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
[        ]              <asynchronous suspension>
[  +17 ms]              #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[  +10 ms]              <asynchronous suspension>
[        ]              #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
[        ]              <asynchronous suspension>
[        ]              #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
[        ]              <asynchronous suspension>
[   +3 ms]              #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]              <asynchronous suspension>
[        ]              #16     main (package:flutter_tools/executable.dart:93:3)
[        ]   [  +15 ms] "flutter assemble" took 391.922ms.
[        ]              <asynchronous suspension>
[        ]   [  +13 ms] 
[   +6 ms]              #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[   +2 ms]              #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:339:7)
[        ]              <asynchronous suspension>
[        ]              #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
[        ]              <asynchronous suspension>
[        ]              #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]              <asynchronous suspension>
[        ]              #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]              <asynchronous suspension>
[        ]              #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
[        ]              <asynchronous suspension>
[  +16 ms]              #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]              <asynchronous suspension>
[        ]              #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
[        ]              <asynchronous suspension>
[        ]              #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
[        ]              <asynchronous suspension>
[        ]              #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]              <asynchronous suspension>
[        ]              #10     main (package:flutter_tools/executable.dart:93:3)
[        ]              <asynchronous suspension>
[  +83 ms]   [ +168 ms] ensureAnalyticsSent: 164ms
[        ]   [        ] Running 0 shutdown hooks
[        ]   [        ] Shutdown hooks complete
[        ]   [        ] exiting with code 1
[...]`

**Comment by TrueHorse** [comment]
Ok, I just tried again and just let it run in the background with Language_de_1996() and it completed the aot_elf_release build after about one hour.

**Comment by TrueHorse** [comment]
Without it aot_elf_release completes in about 30 seconds.

**Comment by TrueHorse** [comment]
Someone from the dart team said they might be able to change something in the compiler, but that he would suggest to represent the language data differtently, for example as a json:
https://github.com/flutter/flutter/issues/150182#issuecomment-2165616057

**Comment by TrueHorse** [comment]
Unfortunately that doesn't look good, because the text is not there for the first fraction of a second, making that part of the UI jump around, but I get that you don't care that much about this project anymore so I will just not use hyphened text there for now.
Have a nice day.

**Comment by TrueHorse** [comment]
I used the TextHyphonated widget, which was in a Row with other stuff, making the other stuff jump to the right when the text finished hyphonating and appeared to their left, instead of them appearing at the same time, which is why I wanted to do it synchronously with the code above.
